# Generated by Django 6.0.2 on 2026-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recp_name', models.CharField(max_length=100)),
                ('recp_desc', models.TextField()),
                ('recp_imag', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
